#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#

def bonAppetit(bill, k, b):
    # Write your code here
    sum0=0
    for j in bill:
        sum0+=j
        
    bill.remove(bill[k])
    sum1=0
    for i in bill:
        sum1+=i
    if sum1/2==b:
        print("Bon Appetit")
    else:
        result=b-sum1/2
        print(int(result))
        

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
