#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    level=0
    levelIndex=[]
    counter=0
    for i in path:
        if i=="U":
            level=level+1
            levelIndex.append(level)
        elif i=="D":
            level-=1
            levelIndex.append(level)
    for t in range(len(levelIndex)):
        if levelIndex[t]==0:
            if levelIndex[t-1]+1==0:
                counter+=1
    return counter

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
