#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'cutTheSticks' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def cutTheSticks(arr):
    # Write your code here
    yeniliste=[]
    result=[len(arr)]
    while len(arr)!=0:
        for i in arr:
            i=i-min(arr)
            if i!=0:
                yeniliste.append(i)
        if len(yeniliste)!=0:
            result.append(len(yeniliste))
        arr=yeniliste
        yeniliste=[]
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
