#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pozitive=0
    negative=0
    zero=0
    for i in arr:
        if i>0:
            pozitive+=1
        elif i==0:
            zero+=1
        elif i<0:
            negative+=1
    print(format(pozitive/len(arr),'.6f'))
    print(round(negative/len(arr),len(arr)))
    print(round(zero/len(arr),len(arr)))
            
   

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
